### ISSUE TITLE
ROCKY-8/RHEL-8: "TASK [../roles/wazuh/wazuh-indexer : Copy the node & admin certificates to Wazuh indexer cluster]" failes due to wrong copy block

### ISSUE THREAD

**Issue by SirStephanikus** [wazuh/wazuh-ansible#1175]
The Task:
```
TASK [../roles/wazuh/wazuh-indexer : Copy the node & admin certificates to Wazuh indexer cluster]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [rocky-8] (item=root-ca.pem) => {"ansible_loop_var": "item", "changed": false, "item": "root-ca.pem", "msg": "Could not find or access '/playbooks/indexer/certificates/wazuh-certificates/root-ca.pem' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [rocky-8] (item=root-ca.key) => {"ansible_loop_var": "item", "changed": false, "item": "root-ca.key", "msg": "Could not find or access '/playbooks/indexer/certificates/wazuh-certificates/root-ca.key' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [rocky-8] (item=node-1-key.pem) => {"ansible_loop_var": "item", "changed": false, "item": "node-1-key.pem", "msg": "Could not find or access '/playbooks/indexer/certificates/wazuh-certificates/node-1-key.pem' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [rocky-8] (item=node-1.pem) => {"ansible_loop_var": "item", "changed": false, "item": "node-1.pem", "msg": "Could not find or access '/playbooks/indexer/certificates/wazuh-certificates/node-1.pem' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [rocky-8] (item=admin-key.pem) => {"ansible_loop_var": "item", "changed": false, "item": "admin-key.pem", "msg": "Could not find or access '/playbooks/indexer/certificates/wazuh-certificates/admin-key.pem' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [rocky-8] (item=admin.pem) => {"ansible_loop_var": "item", "changed": false, "item": "admin.pem", "msg": "Could not find or access '/playbooks/indexer/certificates/wazuh-certificates/admin.pem' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```

fails, due to a wrong copy block inside the wazuh-indexer playbook:

The yaml file `local_actions.yml` and this part:
```

- name: Copy the node & admin certificates to Wazuh indexer cluster
  copy:
    src: "{{ local_certs_path }}/wazuh-certificates/{{ item }}"
    dest: "{{ indexer_conf_path }}/certs/"
    owner: wazuh-indexer
    group: wazuh-indexer
    mode: 0400
  with_items:
    - root-ca.pem
    - root-ca.key
    - "{{ indexer_node_name }}-key.pem"
    - "{{ indexer_node_name }}.pem"
    - admin-key.pem
    - admin.pem
```
Expects the certificate files in my local directory (my workstation) ... but the folder is empty.

The stacktrace prooves it:
```
The full traceback is:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ansible/9.1.0/libexec/lib/python3.12/site-packages/ansible/plugins/action/copy.py", line 466, in run
    source = self._find_needle('files', source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible/9.1.0/libexec/lib/python3.12/site-packages/ansible/plugins/action/__init__.py", line 1429, in _find_needle
    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible/9.1.0/libexec/lib/python3.12/site-packages/ansible/parsing/dataloader.py", line 341, in path_dwim_relative_stack
    raise AnsibleFileNotFound(file_name=source, paths=[to_native(p) for p in search])
ansible.errors.AnsibleFileNotFound: Could not find or access '//playbooks/indexer/certificates/wazuh-certificates/admin.pem' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [rocky-8] (item=admin.pem) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "dest": "/etc/wazuh-indexer/certs/",
        "group": "wazuh-indexer",
        "mode": 256,
        "module_args": {
            "dest": "/etc/wazuh-indexer/certs/",
            "group": "wazuh-indexer",
            "mode": 256,
            "owner": "wazuh-indexer",
            "src": "/playbooks/indexer/certificates/wazuh-certificates/admin.pem"
        },
        "owner": "wazuh-indexer",
        "src": "/playbooks/indexer/certificates/wazuh-certificates/admin.pem"
    },
    "item": "admin.pem",
    "msg": "Could not find or access '/playbooks/indexer/certificates/wazuh-certificates/admin.pem' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
}
```

**Comment by davidcr01** [comment]
Hello. To help you with this problem, I would need to know which playbook are you using, and if you are following our official documentation of the Wazuh ansible deployment option:
- [GitHub documentation.](https://github.com/wazuh/wazuh-ansible/tree/master#documentation)
- [Wazuh Ansible documentation](https://documentation.wazuh.com/current/deploying-with-ansible/index.html)

Also, could you tell me which Wazuh version are you trying to deploy, please?

Apart from this, this task called `Copy the node & admin certificates to Wazuh indexer cluster` is executed at the `security_actions.yml` file of the `wazuh-indexer` role. However, before executing this task (copying the certificates), the certificates are created in a previous task called `Local action | Generate the node & admin certificates in local` in the `local_actions.yml` file.

The generation of the certificates:
https://github.com/wazuh/wazuh-ansible/blob/9fdaac9a260190d4e1fdf169499367d640032148/roles/wazuh/wazuh-indexer/tasks/local_actions.yml#L38-L40

The copy of the certificates:
https://github.com/wazuh/wazuh-ansible/blob/9fdaac9a260190d4e1fdf169499367d640032148/roles/wazuh/wazuh-indexer/tasks/security_actions.yml#L21-L34

Then, in the `main.yml` file of the `wazuh-indexer` tasks, the local actions are executed before the security actions:
https://github.com/wazuh/wazuh-ansible/blob/9fdaac9a260190d4e1fdf169499367d640032148/roles/wazuh/wazuh-indexer/tasks/main.yml#L13-L15
https://github.com/wazuh/wazuh-ansible/blob/9fdaac9a260190d4e1fdf169499367d640032148/roles/wazuh/wazuh-indexer/tasks/main.yml#L52-L54

The problem is that the certificates were created previously, and then in other executions, they were not created again nor copied to the nodes. The approach here is to remove the `playbooks/indexer` folder that should be created in the execution and re-launch the playbook again. The certificates will be created and copied as expected.

**Comment by SirStephanikus** [comment]
Thanks for the response. I installed the certificates manually and wrote my own playbook.
As side information, I used the latest "branch" instead of the tag 4.7.1. 
The “latest” tag was responsible for various other issues.
