### ISSUE TITLE
kibana[20009]:  FATAL  Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by ddean1984** [wazuh/wazuh-ansible#608]
Using the supplied code I am running into an issue on my Kibana server where it will not start. The issue is kibana[20009]:  FATAL  Error: EISDIR: illegal operation on a directory, read. The files that are being looked at are:

at Object.readSync (fs.js:498:3)\n    at tryReadSync (fs.js:332:20)\n    at readFileSync (fs.js:369:19)\n    at readFile (/usr/share/kibana/src/core/server/elasticsearch/elasticsearch_config.js:374:31)\n    at readKeyAndCerts (/usr/share/kibana/src/core/server/elasticsearch/elasticsearch_config.js:358:21)\n    at new ElasticsearchConfig (/usr/share/kibana/src/core/server/elasticsearch/elasticsearch_config.js:293:9)\n    at MapSubscriber.ElasticsearchService.config$.coreContext.configService.atPath.pipe.rawConfig [as project] (/usr/share/kibana/src/core/server/elasticsearch/elasticsearch_service.js:59:108)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at DistinctUntilChangedSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/kibana/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at ReplaySubject._subscribe (/usr/share/kibana/node_modules/rxjs/internal/ReplaySubject.js:76:28) errno: -21, syscall: 'read', code: 'EISDIR' }"}

It appears that modifying the path.data entry in kibana.yml will fix the issue, but my kibana.yml file does not have that entry listed. I have compared my code to this repository and I was unable to find any differences that should cause the issue.

Still searching for the fix, but having a time making any progress. Appreciate any help.

**Comment by ddean1984** [comment]
This issue was related to the previous X-pack configuration. Removed the config and the service started.
