### ISSUE TITLE
Python modue 'wazuh' is not prepared 

### ISSUE THREAD

**Issue by badfiles** [wazuh/wazuh-ansible#772]
In release 4.3.0 the user creation script fails, where should module 'wazuh' come form?
```
TASK [wazuh_manager : Execute create_user script] *********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
failed: [*****] (item={'username': 'wazuh', 'password': '*****'}) => {"ansible_loop_var": "item", "changed": true, "item": {"password": "*****", "username": "wazuh"}, "msg": "non-zero return code", "rc": 1, "stderr": "Shared connection to ***** closed.\r\n", "stderr_lines": ["Shared connection to ***** closed."], "stdout": "\r\nERROR:root:No module 'wazuh' found.\r\n", "stdout_lines": ["", "ERROR:root:No module 'wazuh' found."]}
```

**Comment by badfiles** [comment]
after I removed the try wrapper for import (python can tell when module is missing)
I got the real error
```
[root@template bin]# ./python3.9 ../../scripts/create_user.py 
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.1-py3.9.egg/api/configuration.py", line 129, in fill_dict
    validate(instance=config, schema=json_schema)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 'api/configuration/ssl/server.key' does not match '^[\\w\\-.]+$'

Failed validating 'pattern' in schema['properties']['https']['properties']['key']:
    {'pattern': '^[\\w\\-.]+$', 'type': 'string'}

On instance['https']['key']:
    'api/configuration/ssl/server.key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/bin/../../scripts/create_user.py", line 15, in <module>
    from wazuh.rbac.orm import create_rbac_db
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.1-py3.9.egg/wazuh/rbac/orm.py", line 24, in <module>
    from api.configuration import security_conf
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.1-py3.9.egg/api/configuration.py", line 280, in <module>
    api_conf = read_yaml_config()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.1-py3.9.egg/api/configuration.py", line 263, in read_yaml_config
    configuration = fill_dict(default_conf, configuration, schema)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.1-py3.9.egg/api/configuration.py", line 131, in fill_dict
    raise APIError(2000, details=e.message)
api.api_exception.APIError: 2000 - Some parameters are not expected in the configuration file (WAZUH_PATH/api/configuration/api.yaml): 'api/configuration/ssl/server.key' does not match '^[\\w\\-.]+$'.
```

**Comment by teddytpc1** [comment]
In addition, please check that the `api.yaml` has the `https` configuration as specified in the documentation:
- https://documentation.wazuh.com/current/user-manual/api/configuration.html

Note that the value for `key`, `cert` and `ca` contains only the file name without the path.

**Comment by teddytpc1** [comment]
Closing due to inactivity. Feel free to reopen it if needed.
