### ISSUE TITLE
Adapt repository to deploy Wazuh 4.4.0

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-ansible#853]
The repository needs to be adapted to deploy Wazuh `4.4.0` using branch `4.4`.
The required change so far is to set `/etc/wazuh-indexer/opensearch-security` to the variable `indexer_sec_plugin_conf_path` for the indexer role.

**Comment by teddytpc1** [comment]
After changing the variable the pipeline failed with the following error when running the `securityadmin` script:

```TXT
09:51:55  Security Admin v7
09:51:55  Will connect to 10.0.2.96:9300 ... done
09:51:55  ERR: An unexpected RuntimeException occured: error while performing request
09:51:55  Trace:
09:51:55  java.lang.RuntimeException: error while performing request
09:51:55  	at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:963)
09:51:55  	at org.opensearch.client.RestClient.performRequest(RestClient.java:332)
09:51:55  	at org.opensearch.client.RestClient.performRequest(RestClient.java:320)
09:51:55  	at org.opensearch.security.tools.SecurityAdmin.execute(SecurityAdmin.java:462)
09:51:55  	at org.opensearch.security.tools.SecurityAdmin.main(SecurityAdmin.java:159)
09:51:55  Caused by: org.apache.http.ProtocolException: Not a valid protocol version: This is not an HTTP port
```

The error will be investigated. Related issue in Opensearch Project:
- https://github.com/opensearch-project/documentation-website/issues/695

**Comment by teddytpc1** [comment]
The package for the Windows Agent failed to build. I will wait until the issue is resolved to continue.

**Comment by teddytpc1** [comment]
I was able to build de Win Agent package and I'm currently testing the Demo deploy pipeline.

**Comment by teddytpc1** [comment]
The Wazuh dashboard service failed. It shows the following errors:

```TXT
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since lun 2022-10-24 16:39:23 UTC; 2h 8min ago
  Process: 18343 ExecStart=/usr/share/wazuh-dashboard/bin/opensearch-dashboards -c /etc/wazuh-dashboard/opensearch_dashboards.yml (code=exited, status=13)
 Main PID: 18343 (code=exited, status=13)

oct 24 16:39:23 ip-10-0-0-158.us-west-1.compute.internal systemd[1]: Stopped wazuh-dashboard.
oct 24 16:39:23 ip-10-0-0-158.us-west-1.compute.internal systemd[1]: Started wazuh-dashboard.
oct 24 16:39:23 ip-10-0-0-158.us-west-1.compute.internal opensearch-dashboards[18343]: OpenSSL configuration error:
oct 24 16:39:23 ip-10-0-0-158.us-west-1.compute.internal opensearch-dashboards[18343]: 140122067044224:error:0200100D:system library:fopen:Permission denied:../deps/openssl/openssl/crypto/bio/bss_file.c:69:fopen('/etc/ssl/openssl.cnf','rb')
oct 24 16:39:23 ip-10-0-0-158.us-west-1.compute.internal opensearch-dashboards[18343]: 140122067044224:error:2006D002:BIO routines:BIO_new_file:system lib:../deps/openssl/openssl/crypto/bio/bss_file.c:78:
oct 24 16:39:23 ip-10-0-0-158.us-west-1.compute.internal opensearch-dashboards[18343]: 140122067044224:error:0E078002:configuration file routines:def_load:system lib:../deps/openssl/openssl/crypto/conf/conf_def.c:170:
oct 24 16:39:23 ip-10-0-0-158.us-west-1.compute.internal systemd[1]: wazuh-dashboard.service: main process exited, code=exited, status=13/n/a
oct 24 16:39:23 ip-10-0-0-158.us-west-1.compute.internal systemd[1]: Unit wazuh-dashboard.service entered failed state.
oct 24 16:39:23 ip-10-0-0-158.us-west-1.compute.internal systemd[1]: wazuh-dashboard.service failed.
```

I will check with the team to check if it is a known error related to any change in the package.

**Comment by teddytpc1** [comment]
After running some tests I found out that the `wazuh-dashboard` service fails after some post-installation tasks. I will perform additional tests to identify what task is the one that make the service fail.

**Comment by teddytpc1** [comment]
The demo deployment is still failing but the `wazuh-ansible` tasks are working fine. The PR will be submitted for review.
